name: Release
on: workflow_dispatch

jobs:

build_nuget:

runs-on: windows-latest

permissions:
actions: write
deployments: write
repository-projects: write
packages: write
contents: write
id-token: write

steps:

- name: Checkout
uses: actions/checkout@v3
with:
fetch-depth: 0

- name: Install .NET Core
uses: actions/setup-dotnet@v3.0.3
with:
dotnet-version: 6.0.x

- name: Create Package
run: dotnet pack
working-directory: PowerCollections

- name: Publish Package
run: dotnet nuget push "*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/Novoselov-Igor/index.json —skip-duplicate
working-directory: PowerCollections\PowerCollections\bin\Debug\

- name: Get XML
id: getxml
uses: mavrosxristoforos/get-xml-info@1.1.1
with:
xml-file: 'PowerCollections/PowerCollections/PowerCollections.csproj'
xpath: '//Version'
- name: Create Release
uses: ncipollo/release-action@v1.12.0
with:
token: ${{ secrets.GITHUB_TOKEN }}
artifacts: 'PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'
tag: ${{ steps.getxml.outputs.info }}

